version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      discovery.type: single-node
    ports:
      - 9300:9300
      - 9200:9200
  apm:
    image: docker.elastic.co/apm/apm-server:7.1.1
    volumes:
      - ./apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
    ports:
      - 8200:8200
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: nokamoto/poc-go-elastic-apm:latest
    environment:
      ELASTIC_APM_SERVICE_NAME: poc-go-elastic-apm
      ELASTIC_APM_SERVER_URL: http://apm:8200
    ports:
      - 9090:9090
    depends_on:
      - apm
